const MEME_slike = [
  { id: 1,  src: "🍎" },
  { id: 2,  src: "🍌" },
  { id: 3,  src: "🍒" },
  { id: 4,  src: "🍇" },
  { id: 5, src: "🍓" },
  { id: 6, src: "🦆" },
  { id: 7,  src: "🙂" },
  { id: 8, src: "😍" },
  { id: 9, src: "🥰" },
  { id: 10, src: "😘" },
  { id: 11, src: "🦉" },
  { id: 12, src: "🐝" },
  { id: 13, src: "🦋" },
  { id: 14, src: "🐢" },
  { id: 15, src: "🐙" },
  { id: 16, src: "🐬" },
  { id: 17, src: "🐳" },
  { id: 18, src: "🐠" },
  { id: 19, src: "🦀" },
  { id: 20, src: "🐞" }
];